version: '3.4'

services:
  catalogdb2container:
    container_name: catalogdb2containername
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog_volume:/var/lib/postgresql/data